### PR TITLE
Set profile field when empty but provided by claims

### PR DESCRIPTION
**Pull request by svrooij**
I've updated the project to set the rest of the profile fields.
This will happen for new users (the profile will not be filled anyway), and existing users (but only if they didn't fill in the fields).

This gives an even better user experience.

Thanks for this plugin, it was a great help!

### CODE REVIEW

**Comment by daggerhart** [comment]
Hi @svrooij 

Thanks for the help, and sorry for the slow reply.

There was recently a pull request #27 committed to the dev branch that accomplishes this. You can see it here: https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client-wrapper.php#L769

I think that will meet your needs, but if you see something missing please let me know.  I plan to merge the recent dev changes into master soon.

Thanks,
Jonathan

**Comment by svrooij** [comment]
Hello Jonathan,

In a corporate environment (where SSO is the standard) it might not be desired for users to be able to change their Wordpress profile.
My pull request cleared the way for setting all the properties on every login.

This could be an extra option in the plugin settings, like 'force openid profile'.

This could also be implemented by some actions, but it seems like the update action doesn't get all the claims?

**Comment by daggerhart** [comment]
Ahh yes, that feature makes great sense to me.

Now I see where you were executing the new method in a few places that are commented out, like here: https://github.com/daggerhart/openid-connect-generic/pull/29/files#diff-0269751afd8c9279a042eaf21267c86eR370

Describing it as a setting the site administrator can choose to enable sounds great to me. Do you want to take a crack at doing it that way? If you don't have time and just need this feature soon, I'm happy to make it happen.

Also, 2 tiny notes on future pull requests:

1. Can you make them against the `dev` branch in the repo
2. Is there a way to setup your editor so it doesn't make whitespace changes to the code? Almost every blank line in this PR has been altered by your editor making it bit difficult to see what was actually changed.

Thanks again, let me know if you want me to implement this feature.
Jonathan

**Comment by robbiepaul** [comment]
You could achieve this already by hooking in to the actions provided by the plugin in your own theme or plugin.

For example:
```php
add_action('openid-connect-generic-update-user-using-current-claim', 'updateUser', 10, 2);
add_action('openid-connect-generic-user-create', 'updateUser', 10, 2);

function updateUser($user, array $user_claims)
{
    $update_userdata = array();
    $update_userdata['ID'] = $user->ID;
    if($user->user_login == $user->display_name && !empty($user_claims['name'])){
        $update_userdata['display_name'] = $user_claims['name'];
    }
    if(empty($user->first_name) && !empty($user_claims['given_name'])){
        $update_userdata['first_name'] = $user_claims['given_name'];
    }
    if(empty($user->last_name) && !empty($user_claims['family_name'])){
        $update_userdata['last_name'] = $user_claims['family_name'];
    }
    wp_update_user($update_userdata);
}
```

I personally feel like this type of logic should remain outside of an authentication plugin as not everyone will want to have the same thing. For example one user might not want to have family name saved. A setting to enable/disable it would be okay though.

Just my two pence, thanks again for maintaining the plugin!

**Pull request closed without merging**
