### PR TITLE
More flexible identity settings.

### PR DESCRIPTION
**Pull request by moriyoshi**
This patch adds the following new settings:

* nickname_key

  Where in the user claim array to find the user's nickname.
  Possible standard values: `preferred_username`, `name`, or `sub`.

* email_format

  The string from which the user's email address is built.   Placeholders like `"{claim_name}"` are allowed.  Specify `"{email}"` as long as the user claim contains an email claim.

* displayname_format

  The string from which the user's display name is built.  Placeholders like `"{given_name} {family_name}"` are allowed. 
 
* identify_with_username

  If set to true, the user will be identified according to the username instead of the email address. 

Also, if `given_name` or `family_name` is contained in the user claim, they will be used to populate the new user's first name and last name.

### CODE REVIEW

**Comment by robertstaddon** [comment]
This looks like it could be really helpful. What do you think, @daggerhart ?

**Comment by daggerhart** [comment]
@robertstaddon It does seem useful, I often forget how many different versions of the user's name WP has. 

I don't have time to thoroughly test it for a week or so. @moriyoshi could you provide a little description about what problems this change solves for you, how you use it (with some settings examples), and if/how you think these changes might affect existing sites using this plugin if they update? That would help me understand what to expect when testing it.

Thanks,
Jonathan

**Comment by moriyoshi** [comment]
Okay, here it goes.

`nickname_key` ... the OP may provide a nickname as a claim for the user at userinfo endpoint and it would be handy to adopt it for the nickname at the WordPress side.

`email_format`... the plugin unconditionally uses the email claim for the newly created user's email, but the email address is not guaranteed to be unique amongst other users in the OP, nor is the email claim necessarily provided by the endpoint with the scope specified (because the client does not have the permission. etc.)  In such a scenario, email addresses need to be "synthesized" so they work as identities in WP.

`identify_with_username` ... as explained above, the email address is not always guaranteed to be unique at a specific instance.  In addition to it, if it is unique at some point, it might not be unique over time.   In such a case, username is much more suitable to identify the existing user.

`displayname_format` ... the OpenID specification defines multiple standard claims (`name` `nickname` `given_name` `middle_name` `family_name` and `preferred_usermame`) that would be suitable for the new user's display name besides the OP may provide non-standard claims.  As how the display name should be rendered at the WordPress side is solely subject to the site's discretion, this cannot be a setting that can specify a single claim, but a formatting string.

**Comment by daggerhart** [comment]
Thanks @moriyoshi, that all makes perfect sense to me.  
Merged into dev branch and will test changes against an existing site soon!

**Comment by daggerhart** [comment]
@moriyoshi 
Finally got a chance to explore this. Very nice! I like how the display name essentially allows for any token that exists in the user claim.

Thanks again for the help!

**Pull request merged**
