### PR TITLE
Simplify refresh/logout handling (to fix #49, #50, and #51)

### LINKED ISSUE #49: link_existing_users flag causes orphans sessions if a concurrent session logs out
Currently, the `openid-connect-generic-user` meta flag is set to false when a user logs out (if `link_existing_users` is set), but this doesn't work correctly if a user has more than one login session, because then the other sessions will stop refreshing tokens and act like ordinary Wordpress sessions.  (And thus will remain live with current permissions even if those permissions have been revoked at the IdP.)

Steps to reproduce:

1. Set up a site with Auto-SSO login mode and "link existing users"
2. Log into the site from two different browsers using OIDC, then explicitly log out of one.
3. Wait for the refresh token to expire, then access the site in the second browser.  You *should* get a refresh error, but instead you get a plain WP session unconnected to OIDC.

The problem is that a user meta flag is global to the user, but what is really needed is to know whether the *session* is linked to an OIDC session, not the user as a whole.

For my own purposes, I'm working around this with a `get_user_meta` hook which checks that the session is actually OIDC-linked; it does this by adding data to the WP session token in the database (via the `attach_session_information` hook).  This then results in the OIDC plugin seeing a fake `openid-connect-generic-user` value that reflects whether the session was started with OIDC, instead of a global flag whose value might be corrupt.

This workaround could be avoided, though, by having  `ensure_tokens_still_fresh()` check for a flag in `WP_Session_Tokens::get_instance($user_id)->get(wp_get_session_token())`.  The flag would be set by `login_user()`, either via an `attach_session_information` hook, or by directly creating the session token and passing it through to `wp_set_auth_cookie()`.

### PR DESCRIPTION
**Pull request by pjeby**
This PR simplifies refresh token management, moving it from an encrypted cookie to a session token field on the server (addressing issue #49), and keeping track of the refresh token's expiration time so that it doesn't produce an error trying to refresh with an expired token (#51).  #50 is also fixed, by deferring the token refresh (and therefore logouts) until all WP plugins are finished loading.

As a side effect, the dependency on Defuse is dropped (no more encrypted cookies means no more encryption needed), and two user metadata fields are dropped as well (the flag that was at issue for #49, and the cookie encryption key).

### CODE REVIEW

**Comment by daggerhart** [comment]
I really like this approach. Thanks a lot for the work you've done recently on issues. I'm going to merge this soon and up the version to 3.3. 

One thing I'm not sure of is the removal of the `openid-connect-generic-user` user meta.

On one hand, we probably don't need it. On the other it's "nice to have" at the very least being able to query for which users are oauth users, and could be considered a BC issue if removed (possibly break someone's custom code/process).

I'm tempted to leave it in because I don't see how it hurts to have it. Any thoughts?

**Comment by pjeby** [comment]
So, while I don't personally care (don't have BC issues because I'm still in testing stages), my reasoning for getting rid of it was that it *has no coherent meaning*.  The documentation claimed it meant the user was created by the plugin, but that's not true in the case of linking existing users.

Depending on the state of your settings and the state of any sessions for a user, it could be true or false with **no** correlation whatsoever to whether the user was created by the plugin.  I couldn't come up with any way to document the existing behavior that made any sense, in fact.  The closest you might be able to get is, "if you don't allow linking existing users and you *never* turned that flag on while your site was active, then the flag indicates whether the user was created by the plugin".

It's *possible* that someone is actually using that information, if they have never allowed linking existing users.  However, in that case the flag is rendundant: they could look at say, `openid-connect-generic-subject-identity`, which would not exist unless the user had been created by the plugin.

So, in order to "leave it in", it's necessary to decide on its intended semantics.  Does it really mean "created by the plugin", or does it mean, "has used the plugin to log in at some point"?

Either is possible going *forward*, but only the latter meaning can actually be implemented in a way that fixes existing data.  Essentially, you could add a user_meta hook to force the value to true based on the presence of the subject identity.  That would then always have the "right" meaning, if the intended meaning is "this user has a linked account".

That seemed like a lot of work to go to for a feature I wasn't sure anybody was using, and if they were, they probably had bugs.   :)  Given that the plugin isn't on wordpress.com and thus doesn't auto-update, documenting the issue and bumping the major version should suffice to allow someone time to switch to a more appropriate field.

**Comment by daggerhart** [comment]
Great points. Thank you!

**Comment by pjeby** [comment]
Excellent; this means I can start on a fix for #54, without this PR being a moving target.

**Pull request merged**
