### PR TITLE
Track redirect target across logouts (w/no cookie)

### PR DESCRIPTION
**Pull request by pjeby**
This fixes issue #57, while possibly improving user privacy by not constantly updating a cookie with their location on the site.  :wink:

### CODE REVIEW

**Comment by daggerhart** [comment]
3 months later... thanks for this and the PR, it all makes sense to me. I'll test it this weekend.

Any unexpected side effects you can think of if we merge this, then a site upgrades from the cookie-centric version to this?

**Comment by pjeby** [comment]
If it's unexpected, I'm not sure how I'd know.  ;-)

But the expected effect would be that *in-progress* logins that cross the update boundary (i.e. begin before the update and end after it) would fail.

There may be some minor spec compliance issues remaining with this PR, though I think fewer so than without it.  If I were writing this today, I'd instead use the approach I used in [oidc-sso](/dirtsimple/oidc-sso), which is to set a short-lived cookie during the login process and generate a hash from it to use as the state, which is then verified against the cookie on return from the IdP.

(In addition to being closer to the spec intent for how the state is supposed to be used, that approach has the additional benefit of not needing to store values in server-side transients, thereby avoiding possible race conditions when multiple users are logging in at the same time.)

**Comment by pjeby** [comment]
@cedrox I didn't use it for very long; I am now using https://github.com/dirtsimple/oidc-sso instead, which encodes the redirect as part of the state passed to the IdP, and does not use a redirect targeting cookie.

**Comment by cedrox** [comment]
Thanks @pjeby
Just wanted to add that I finally manage to use cookie redirect .
Concerning GDPR, do you think that this can be considered essential?
Thanks

**Comment by pjeby** [comment]
I am not a lawyer and thus cannot offer any legal advice.

**Pull request closed without merging**
