### PR TITLE
Refresh tokens when needed instead of logging out when access_token expires

### PR DESCRIPTION
**Pull request by rwasef1830**
Hello,
This fixes an issue where the user is logged out when the access_token expires (expires_in). Typically this time is very short (~ 5 minutes).

- refresh_token + access_token expiry is sent via encrypted cookie to the browser.
- If cookie is missing or invalid, user is logged out.
- If last access token expired, use refresh token to fetch a new one and send a new cookie.
- If token refresh fails, user is logged out.
- Cookie encryption is with per-user random key stored in user meta.
- Encryption and key generation done using https://github.com/defuse/php-encryption
- Updated autoloader function to support loading namespaced classes.

### CODE REVIEW

**Comment by robertstaddon** [comment]
Wow, this is a pretty big pull request, @rwasef1830 . Thank you for this development work. Do you have this working in a production environment? @daggerhart , what do you think about this direction?

**Comment by rwasef1830** [comment]
@robertstaddon No, I just wrote this because I found that this plugin is pretty unusable for me out of the box with keycloak. It works for me in local testing, but I haven't put it in production yet, there are more changes needed before it can be usable for me. (I will open more issues / pull requests later with those changes).

As it stands, the plugin uses the authorization code flow to get a token response. In most cases (and this is encouraged by the OpenID Connect spec), the access token expiry (expires_in) is very short-lived (usually around 5 minutes), and the plugin enforces a logout by using a secondary cookie with expiry equal to the access token expiry. However, the user is still logged in the IdP, so I think it is not correct to log out the user from WordPress then.

This pull request stores the refresh token securely in the user's browser (I opted to use a well-known encryption library instead of rolling my own to avoid subtle vulnerabilities), and used it to refresh the token. When refresh fails, this means the user's SSO session in the IdP is no longer valid, only then it becomes correct behavior to log the user out.

I appreciate any feedback and suggestions :-)

**Comment by robertstaddon** [comment]
@daggerhart , I'm inclined to merge this pull request. The approach that @rwasef1830 is taking here does make a lot of sense to me. @rwasef1830 , do you have any security concerns with storing the refresh token in the user's browser? It's not like you can obtain the user's username/password from this or anything, correct?

**Comment by rwasef1830** [comment]
@robertstaddon the security concern is that if the refresh token is stolen, the attacker will have access to everything the user's token (depending on the requested scope configured in the plugin for wordpress) has access to. To solve this, the refresh token is encrypted with a per-user encryption key stored in the user's meta table and decrypted on each request to extract the user's refresh token, so with my approach the refresh token is never stored in plain text anywhere (the cookie contains an encrypted form).

**Comment by robertstaddon** [comment]
Ok, I'm going to go ahead and merge this in and we'll see how it goes. @rwasef1830 , please keep us posted on any continued development and bug fixes.

**Comment by daggerhart** [comment]
@rwasef1830  Thanks, this looks great! I'd wanted to do refresh tokens but hadn't gotten around to it. Code looks great, use of library for encryption is ideal. 

@robertstaddon thanks for merging this to dev, and sorry for the slow reply. I'll start testing this today.

One concern I have is that refresh tokens are option for an IDP: https://tools.ietf.org/html/rfc6749#section-1.5
> Issuing a refresh token is optional at the discretion of the authorization server.

Unless I'm mistaken, I think we need to allow for both cases to work (with, and without refresh tokens). Any thoughts (or experience) on how to approach this?  Should we have a new setting "Re-authorize using Refresh Tokens", or should we try to make it more automatic?

Thanks again for all the help!

**Comment by rwasef1830** [comment]
Hmmmm... you're right. If the offline_access scope is not requested, the
refresh token is optional. In that case I guess it should be more
automatic. I'll implement this and make another pull request.

**Comment by rwasef1830** [comment]
@daggerhart Created #22 with handling of missing refresh_token

**Pull request merged**
